import funcoes_erro
funcoes_erro()
